# Generated by Django 5.1.3 on 2024-12-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_remaning_credit_customer_total_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='particulars',
            field=models.CharField(default=' ', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='debit',
            name='particulars',
            field=models.CharField(default='Cheque', editable=False, max_length=255),
        ),
    ]
