# Generated by Django 5.1.3 on 2024-12-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_billitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
