# Generated by Django 5.1.3 on 2024-12-05 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_customer_credit_remove_customer_debit_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='date',
            field=models.DateField(default=datetime.date(2024, 12, 5)),
        ),
        migrations.AddField(
            model_name='debit',
            name='date',
            field=models.DateField(default=datetime.date(2024, 12, 5)),
        ),
        migrations.AlterField(
            model_name='credit',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='debit',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
