# Generated by Django 5.1.3 on 2024-12-05 03:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_credit_date_debit_date_alter_credit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='debit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
